### ISSUE TITLE
Forward ref

### ISSUE THREAD

**Issue by pro0255** [atlasgroupcz/react-atlantic#170]
Add **forwardRef** on every component.

Otherwise some components must be wrapped with TooltipRoot. (example: _Button_)

**Comment by topolanekmartin** [comment]
I found a use case when I needed forwardRef on wrap utility function. Can we add this to the list? :)

**Comment by filipkastovsky** [comment]
@topolanekmartin @pro0255 An alternative pattern would be to pass the ref as a named prop (think `innerRef` or similar). This is an old pattern, but useful. May even reduce boilerplate in some cases over `React.forwardRef` and will definitely work with `wrap`.

I am looking forward to detach `wrap` from `react-atlantic` in the future, as it is useful even beyond the lib. Potential updates to `wrap` include memoized wrap, ref-forwarding wrap as well as some test utils. I will make an issue specifically for discussing `wrap` #209.
