### ISSUE TITLE
Icon cursor

### ISSUE THREAD

**Issue by topolanekmartin** [atlasgroupcz/react-atlantic#228]
Change `Icon.style.ts` file.

Rewrite CSS properity from `cursor: auto;` to `cursor: inherit;`.

**Comment by aniruddhabagal** [comment]
Hey, There is no `cursor: auto;` code in `Icon.Style.ts`.
Please check out. If I am missing out then please guide me, I am relatively new here. :)

**Comment by topolanekmartin** [comment]
This is already done.
